name: ChromeDriver Version Bump
on:
  schedule:
  - cron: "0 0 * * *"

env:
  API_URL: https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json
  CD_VERSIONS_MAPPING: config/mapping.json
  PYTHON_VERSION: "3.8"

jobs:
  bump_cd_version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - id: release_check
      run: |
        export latest_release=$(curl -sf ${{ env.API_URL }} | jq .channels.Stable.version | tr -d '"' )
        export did_update=$(python "scripts/update_versions_mapping.py" "$latest_release" "${{ env.CD_VERSIONS_MAPPING }}")

        echo "did_update=${did_update}" >> "$GITHUB_OUTPUT"
        echo "cd_release=${latest_release}" >> "$GITHUB_OUTPUT"
    - name: pull-request
      if: steps.release_check.outputs.did_update == '1'
      uses: peter-evans/create-pull-request@v3
      with:
        branch: ${{ steps.release_check.outputs.cd_release }}
        title: "chore: ChromeDriver Bump to v${{ steps.release_check.outputs.cd_release }}"
        body: ""
